improve pipeline

diff --git a/.github/workflows/update-bangs.yml b/.github/workflows/update-bangs.yml
--- a/.github/workflows/update-bangs.yml
+++ b/.github/workflows/update-bangs.yml
@@ -5,32 +5,71 @@ on:
     - cron: '0 0 * * *'
   workflow_dispatch:
 
+env:
+  BANGS_DOWNLOAD_URL: https://duckduckgo.com/bang.js
+  BANGS_FILE_PATH: assets/bangs.json
+
 jobs:
-  update-data:
+  download-bangs:
+    name: Download Bangs
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download Bangs
+        run: curl -sSL ${{ env.BANGS_DOWNLOAD_URL }} ${{ env.BANGS_FILE_PATH }}
+
+      - name: Validate json
+        run: |
+          if ! jq empty ${{ env.BANGS_FILE_PATH }}; then
+            echo "❌ Invalid JSON. Aborting."
+            exit 1
+          fi  
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        with:
+          path: ${{ env.BANGS_FILE_PATH }}
+
+  diff-check:
+    name: Diff check
+    needs: download-bangs
+    runs-on: ubuntu-latest
+    outputs:
+      data_changed: ${{ steps.diff-check.outputs.data_changed }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Download artifact
+        uses: actions/download-artifact@v4
+        with:
+          path: ${{ env.BANGS_FILE_PATH }}
+
+      - name: Check for differences
+        id: diff-check
+        run: |
+          if git diff --quiet; then
+            echo "data_changed=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "data_changed=false" >> "$GITHUB_OUTPUT"
+          fi 
+  
+  
+  push-changes:
+    name: Push updated Bangs
+    needs: diff-check
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Download artifacts
+        uses: actions/download-artifact@v4
         with:
-          persist-credentials: false
-
-      - name: Download Bangs
-        run: curl -sSL https://duckduckgo.com/bang.js -o assets/bangs.json
-
-      - name: Validate json
-        run: |
-          if ! jq empty assets/bangs.json; then
-            echo "❌ Invalid JSON. Aborting."
-            exit 1
-          fi  
-
-      - name: Check for changes
-        run: |
-          if git diff --quiet; then
-            echo "No changes in data.json"
-            exit 78
-          fi     
+          path: ${{ env.BANGS_FILE_PATH }}
 
       - name: Commit and push
         env:
